/**
 * Returns the .gitignore content for producer repos.
 * Ignores build artifacts and CI-generated release assets.
 */
export function getProducerGitignore(): string {
  return `# Dependencies
node_modules/

# Build output (regenerated by clafoutis generate)
build/

# CI-generated release assets
release-assets/
`;
}

/**
 * Returns the .gitignore content for consumer repos.
 * Only ignores the cache file.
 */
export function getConsumerGitignore(): string {
  return `# Clafoutis cache
.clafoutis/cache
`;
}
