#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Load nvm and use the correct Node version from .nvmrc
export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && nvm use

make pre-commit
